server:
  port: 8990

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  application:
    name: KAFKA_PRODUCER
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers:
        - localhost:9092
        - localhost:9093
        - localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

event:
  producer:
    topic: library-events